version: "3.7"

services:
  mysql:
    container_name: mysql
    image: mysql/mysql-server:8.0
    restart: unless-stopped
    volumes:
      - mysql-data:/var/lib/mysql
      - ./backup/:/usr/local/data/mysql/backup
      - ./my.cnf:/etc/my.cnf
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
volumes:
  mysql-data:
    driver: local
