resource "local_file" "inventory" {
  content = <<-DOC
    # Ansible inventory containing variable values from Terraform.
    # Generated by Terraform.
    ---
    lighthouse:
      hosts:
        lighthouse01:
          ansible_host: ${yandex_compute_instance.lighthouse01.network_interface.0.nat_ip_address}
          ansible_user: centos
    clickhouse:
      hosts:
        clickhouse01:
          ansible_host: ${yandex_compute_instance.clickhouse01.network_interface.0.nat_ip_address}
          ansible_user: centos
    vector:
      hosts:
        vector01:
          ansible_host: ${yandex_compute_instance.vector01.network_interface.0.nat_ip_address}
          ansible_user: centos
    DOC
  filename = "../ansible/inventory"

  depends_on = [
    yandex_compute_instance.lighthouse01,
    yandex_compute_instance.clickhouse01,
    yandex_compute_instance.vector01
  ]
}
