# -*- mode: ruby -*-

ISO = "centos/8"
NET = "192.168.56."
INVENTORY_PATH = "../ansible/inventory"

servers = [
  {
    :hostname => "clickhouse-01",
    :ip => NET + "11",
    :ssh_host => "20011",
    :ssh_vm => "22",
    :ram => 1024,
    :core => 1
  },
  {
    :hostname => "vector-01",
    :ip => NET + "12",
    :ssh_host => "20012",
    :ssh_vm => "22",
    :ram => 1024,
    :core => 1
  }
]

Vagrant.configure(2) do |config|
  config.vm.synced_folder ".", "/vagrant", disabled: false
  servers.each do |machine|
    config.vm.define machine[:hostname] do |node|
      node.vm.box = ISO
      node.vm.hostname = machine[:hostname]
      node.vm.network "private_network", ip: machine[:ip]
      node.vm.network :forwarded_port, guest: machine[:ssh_vm], host: machine[:ssh_host]
      node.vm.provider "virtualbox" do |vb|
        vb.memory = machine[:ram]
        vb.cpus = machine[:core]
        vb.name = machine[:hostname]
      end
      node.vm.provision "ansible" do |setup|
        setup.verbose = "v"
        setup.inventory_path = INVENTORY_PATH
        setup.playbook = "../ansible/provision.yml"
        setup.become = true
        setup.extra_vars = { ansible_user: 'vagrant' }
      end
    end
  end
end
